### ISSUE TITLE
Nagflux doesn't work with influxDB/https and auto-signed certificat

### ISSUE THREAD

**Issue by jframeau** [Griesbacher/nagflux#12]
Hi,

config: 

- influxdb  0.13 / https API configured with auto-signed certificate (influxdb on remote host)

From github, nagflux can't connect to influxdb as go http client denies access to such https connector.

I managed to add a bit of code to skip certicate check:

--- a/target/influx/Connector.go
+++ b/target/influx/Connector.go
@@ -1,6 +1,7 @@
 package influx
 
 import (
+       "crypto/tls"
        "encoding/json"
        "github.com/griesbacher/nagflux/collector"
        "github.com/griesbacher/nagflux/data"
@@ -43,7 +44,15 @@ func ConnectorFactory(jobs chan collector.Printable, connectionHost, connectionA
                }
        }
        timeout := time.Duration(5 * time.Second)
-       client := http.Client{Timeout: timeout}
+       tlsConfig := &tls.Config{
+               InsecureSkipVerify: true,
+       }
+
+       tr := &http.Transport{
+               TLSClientConfig: tlsConfig,
+       }
+
+       client := http.Client{Timeout: timeout, Transport: tr}

After that, nagflux connection went well, but nagflux failed to create the database:

2016-08-23 12:15:55 Info: good
2016-08-23 12:15:55 Info: Influxdb running
2016-08-23 12:16:05 Panic: Database does not exists and was not able to created
panic: Database does not exists and was not able to created

 Any idea to get https working ?

jfr

**Comment by Griesbacher** [comment]
I'll have a look at it, but I'm pretty sure that self signed certificates won't work at the moment.

**Comment by Griesbacher** [comment]
I didn't use that http.Client properly... There is a fix, so if you build it on your own, you could test it. Let me know if there are any further problems.

**Comment by jframeau** [comment]
Ok, thx, nagflux works nicely with influxdb/https autosigned certificate now.

Just a little trouble when influxdb is not started:

```
        if !s.isAlive {
                s.log.Info("Waiting for InfluxDB server")
        }

        for i := 0; i < 12 && !s.isAlive; i++ {
                s.TestIfIsAlive()
-               time.Sleep(5)
+               time.Sleep(time.Duration(5) * time.Second)
                s.log.Info(".")
        }


```

**Comment by jframeau** [comment]
Also, out of curiosity, is there a point to not use official Influxdb go client library : https://github.com/influxdata/influxdb/tree/master/client ?

**Comment by Griesbacher** [comment]
Thanks for the bug fix!
The Influxdb client library was still under development when I started and it changed a lot of times, so I decided to do it on my own, due to the fact there was no vendor option in go this can be very annoying.

**Comment by blakec-som** [comment]
@jframeau wondering if you can share your Connector.go file? I'm having this exact issue and can't quite figure out what changes to make.
