### ISSUE TITLE
PNP Converter ?

### ISSUE THREAD

**Issue by Mikesch-mp** [Griesbacher/nagflux#21]
Hello,

is there any chance we get an converter to move all pnp rrd's to influx ?

Best regards,
Carsten

**Comment by sni** [comment]
There is a `migrate_pnp_to_nagflux` in OMD. It might work outside of OMD as well, but you have to adjust some paths.
Source: https://github.com/ConSol/omd/blob/labs/packages/nagflux/migrate_pnp_to_nagflux

**Comment by Griesbacher** [comment]
Exactly, that's the only way I'm currently aware of. There is no way to do this directly with Nagflux and no need for.

**Comment by Mikesch-mp** [comment]
Thank you for the tipp, 114GB of old rrd's are getting converted now :)
