### ISSUE TITLE
Write metrics to different influxdb databases

### ISSUE THREAD

**Issue by adrianlzt** [Griesbacher/nagflux#25]
I have discovered this project while making a PR to [mod_gearman](https://github.com/sni/mod_gearman/pull/108).

I'm trying also to send icinga perfdata to InfluxDB, but I need to send each perfdata to a different database based on a custom template defined in each host.

Any idea if it will be possible to handle this with nagflux?

Thanks!

**Comment by Griesbacher** [comment]
Hi,
at the moment it not possible to do that, if mod_gearman is not able to do so. You could only collect the data from multiple mod_gearman servers but send them just to one InfluxDB. But we were already talking about something like that and I'll add such feature when I'm back to work, in a some weeks.
I was thinking about something like, multiple named serverconfigs within the nagflux config and if such a name is passed by a perfdata the data will be send to the corresponding InfluxDB. If the field is empty the default InfluxDB will be chosen.
Greetings Philip

**Comment by adrianlzt** [comment]
And choosing the influxdb databse with a custom variable?
@sni is thinking in expanding mod_gearman to be able to add custom variables: https://github.com/sni/mod_gearman/pull/108#issuecomment-277254165

**Comment by Griesbacher** [comment]
Exactly, e.g. you're setting a customvariable like NAGFLUX::TARGET to server1, then nagflux would send the data to the server1, which config/address is stored in a the nagflux config

**Comment by sni** [comment]
It would be possible if Mod-Gearman had a customizable performance data template so you could just define the data like ex.: ...NAGFLUX:DB=$_HOSTINFLUXDB$ or something like that.

**Comment by adrianlzt** [comment]
That would be perfect

**Comment by adrianlzt** [comment]
Any update on this?
Thanks

**Comment by Griesbacher** [comment]
I'll be back at the office in one week and tackle the problem then. It's not forgotten.

**Comment by Griesbacher** [comment]
The latest release should solve this issue.
