### ISSUE TITLE
using nagflux with nagios NPCDMOD

### ISSUE THREAD

**Issue by VenkiSa** [Griesbacher/nagflux#28]
we are using Nagios Core 3.5.1, with NPCD and NPCDMOD for pnp4nagios. as far as I understood npcdmod will write perfdata to /var/spool/pnp4nagios. and npcd will process it for graphing. 

Is it possible to make npcdmod to write another spool ? . so that i can use it for nagflux.

or any other solutions make nagflux work in this mode ? 

I have tried adding another npcmod.o broker moduler in /etc/nagios.cfg , but it is breaking pnp4nagios. 

broker_module=/usr/lib64/nagios/brokers/npcdmod.o config_file=/etc/nagflux/npcd.cfg

please share your ideas on it.

**Comment by Griesbacher** [comment]
Hi,
if you want to use both Nagflux and PNP you could use some simple copy script to duplicate the data.
If you want to use just Nagflux, you have to set the path in the Nagflux config and disable PNP.

Have a look at OMD Labs there you could choose between Nagflux and PNP via some simple config menu.

Best Regards,
Philip
