### ISSUE TITLE
Unable to find nagflux binary to start the service

### ISSUE THREAD

**Issue by ranjithkodumbu** [Griesbacher/nagflux#37]
Hi All,

I am unable to find nagflux binary script to start the service. Could you please have a look asap.

Thanks,
Ranjith Kumar R

**Comment by Griesbacher** [comment]
Hi Ranjith Kumar R,

simple answer, there is currently none in the git repository. You have to build it on your own like described here: https://github.com/Griesbacher/nagflux#install

Best Regards,
Philip

**Comment by Griesbacher** [comment]
The current release contains a prebuild binary: https://github.com/Griesbacher/nagflux/releases/tag/v0.4.1

Furthermore the CI Tests create also a binary, see: https://circleci.com/gh/Griesbacher/nagflux
