### ISSUE TITLE
[Question] Can nagflux and pnp4nagios use same spool folder / perf data ? 

### ISSUE THREAD

**Issue by bingoarun** [Griesbacher/nagflux#39]
In the manual setup instructions - https://exchange.nagios.org/directory/Documentation/Nagios-with-InfluxDB,-nagflux-and-Grafana/details, I can see there are additional steps to make a copy of the spool folder so that pnp4nagios and nagflux use different folders. 

Whereas when enabling the nagflux using latest version of omd (omd config set NAGFLUX on), I can see that both pnp4nagios and nagflux are using the same spool folders and both the graphs are working fine.  
Can nagflux and pnp4nagios use same spool folder ?

**Comment by Griesbacher** [comment]
They can use both the same folder but they should not run at the same time. Each tool deletes the spoolfiles after the read, therefore only Nagflux **or** PNP4Nagios receives the data.

If you want to use both, copy the data to two different directories, where each tool can collect the spoolfiles.

**Comment by bingoarun** [comment]
Thank you. We can close this issue.
