### ISSUE TITLE
manual setup problems

### ISSUE THREAD

**Issue by pgroselj** [Griesbacher/nagflux#5]
Hi,

since I'm not using OMD I would like to setup nagflux manually. Running Centos 6 final x64, Nagios Core 3.5.1, Check_MK, installed Golang 1.5.1. 

Tried to run below command which stucks at last line:
[root@nagios~]# go get -v -u github.com/griesbacher/nagflux  
github.com/griesbacher/nagflux (download)
Fetching https://gopkg.in/gcfg.v1?go-get=1
Parsing meta tags from https://gopkg.in/gcfg.v1?go-get=1 (status code 200)
get "gopkg.in/gcfg.v1": found meta tag main.metaImport{Prefix:"gopkg.in/gcfg.v1", VCS:"git", RepoRoot:"https://gopkg.in/gcfg.v1"} at https://gopkg.in/gcfg.v1?go-get=1
gopkg.in/gcfg.v1 (download)

Since I couldn't find a solution for this problem I then did download latest omd-2.01* and found all config files and tried to set them to configure to run it as it should:
-created /var/nagflux, /var/log/nagflux/nagflux.log
-created and edited /etc/logrotate.d/nagflux
-created and edited /etc/init.d/nagflux
-added action_url to my service & host template
-created database called "nagflux" in influxdb

Data is filling in InfluxDB and if I go to Grafana dash I can create new pannel and show mesaured data.

The problem that I cannot resolve is connected with Histou - action url from my host and service is showing graphs but not content during an error. I did check histou.php (i.e. /histou/index.php?host=nagios-ipo&service=CPU%20load) which shows the same data for every service - it allways returns data for check_mk service:

....
[rows] => Array
        (
            [0] => Array
                (
                    [title] => nagios-ipo CPU load check-mk
                    [editable] => 1
                    [height] => 400px
                    [panels] => Array
                        (
                            [0] => Array
                                (
                                    [title] => nagios-ipo CPU load check-mk children_system_time
...

The problem is that the command name and performancelabel are incorrect. If I go to influx cli, and use nagflux and perform command:
select * from metrics where host='nagios-ipo-trap' and service='CPU load' limit 1
name: metrics
-------------
time                    command                 crit    crit-fill       host            max     min     performanceLabel        service         unit      value   warn    warn-fill
1461240500000000000     check_mk-cpu.loads      20      none            nagios-ipo-trap 2       0       load1                   CPU load         10       none

You can see that che command should be check_mk-cpu.loads and the performanceLabel should be load1. Since I had to manually create database named "nagflux" I'm not really sure that something is not missing.

Can you help me?

BR, Peter

**Comment by Griesbacher** [comment]
Hi Peter,

which InfluxDB version are you using? We're currently using only 0.10.X like in the OMD Package.

Normally you don't have to create the database, Nagflux is doing it, but it seams that the data is written correct into the Influxdb but the query from Histou went wrong.

If there's an error Thruk will only show a text message, I guess you're using Thruk. Maybe look into the apache error log, if there is a real php error it should appear there. There is also the url flag "debug" for Histou, where you get a little output as text panel in Grafana.

Maybe that helps a little,
Philip

**Comment by pgroselj** [comment]
Hi,

thanks for fast response. I'm using latest 0.12.1 InfluxDB. I just remebered that for my testing purposes I changed the query in histou/histou/database/influxdb.php and that is why histou.js returned allways the same. Now I changed it back and it's fine.

I tried to open the URL from original Nagios webinterface and now it is fine. But from Check_MK it allways shows the services from service Check_MK (it's perfdata). Can you tell me why?



Action_url is as it should be:
HOST:
  action_url                      /grafana/dashboard/script/histou.js?host=$HOSTNAME$&theme=light
SERVICE:
  action_url                      /grafana/dashboard/script/histou.js?host=$HOSTNAME$&service=$SERVICEDESC$&theme=light

Thanks!

**Comment by pgroselj** [comment]
Oh, this is allready a issue:
https://github.com/influxdata/influxdb/issues/6220

It is a Grafana issue and fixed in It's fixed in Grafana3beta3.

Thanks for all help!

**Comment by Griesbacher** [comment]
Good to hear. I'll upgrade the InfluxDB when Grafana has a stable release, then everything will be updated in OMD as well.

You're welcome, I didn't do much.
