### ISSUE TITLE
[question] nagflux schema in omd

### ISSUE THREAD

**Issue by rockaut** [Griesbacher/nagflux#6]
Hello there,

is there anyway to modify the scheme data ist stored in influxdb? Since 0.9 i think are some additional possibilities (sums, filtering, etc. ) is data would be stores in a more structured way - like: http://stackoverflow.com/questions/33997430/obtaining-a-total-of-two-series-of-data-from-influxdb-in-grafana

Like a memory used check in nagios: there will be the used performance values with value, warning, critical and maximum values provided. Currently each are stored in single measurements like hostname&Memory used&check_mk-esx_vsphere_hostsystem.mem_usage&usage&value
Why not storing those values in tags.

**Comment by Griesbacher** [comment]
Hey,

in Nagflux v0.2.0 I changes the Layout: https://github.com/Griesbacher/nagflux/releases/tag/v0.2.0 so maybe your using an older version. Have a look at it, maybe that's answering your question, if not let me know. If you're using only stable OMD, you'll have to wait for a new release, the "nightly" version has newer versions in it.

**Comment by rockaut** [comment]
Thats great. We're using 2.10 omd Labs edition so it's pretty fresh. But no
troubles or rushing here if know that it's comming.

Thanks for your work.
Am 15.05.2016 7:16 vorm. schrieb "Philip Griesbacher" <
notifications@github.com>:
