### ISSUE TITLE
Project is dead and disfunctional!

### ISSUE THREAD

**Issue by jhofmueller** [Griesbacher/nagflux#61]
This project is **dead** and does **not work** anymore. I would greatly appreciate this fact to be stated here and a link to the successor. Unfortunately there is no working copy of this project anywhere to be found and my understanding/skill of go is too limited to step in here.

I hope this message saves others the time that I wasted in trying to get this thing to run. Bummer.

**Comment by sni** [comment]
We are maintaining it here: https://github.com/ConSol-Monitoring/nagflux
It works well.

**Comment by jhofmueller** [comment]
I have to **disagree**. The project at https://github.com/ConSol-Monitoring/nagflux cannot be used the way it is described in the README (`go get -u github.com/ConSol-Monitoring/nagflux`). Trying `go install` instead leads to `package is not a main package`.
The link to a [Release](https://github.com/ConSol-Monitoring/nagflux/releases/latest) leads to a page with no releases.
If you have any suggestions on howto get it running I'd be grateful. You can also tell me what I am doing wrong if you 
However it looks like *nagflux* is integrated into *OMD* and nobody bothers testing it standalone anymore.
